name: Prod Infra Apply (no plan)

on:
  workflow_dispatch:
    inputs:
      infra_version:
        description: "Infrastructure ref to apply"
        required: true
        default: "main"
        type: string

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  infra:
    name: Apply
    uses: ./.github/workflows/shared_infra_apply_no_plan.yml
    with:
      environment: prod
      infra_version: ${{ inputs.infra_version }}
