name: Shared Directories Get

on:
  workflow_call:
    outputs:
      action_dirs:
        description: "List of repo-local GitHub action directory names with Dockerfiles"
        value: ${{ jobs.directories.outputs.action_dirs }}
jobs:
  directories:
    name: Directories
    runs-on: ubuntu-latest
    outputs:
      action_dirs: ${{ steps.action_dirs.outputs.just_outputs }}
    steps:
      - uses: actions/checkout@v6

      - name: Get Action Directories
        id: action_dirs
        uses: ./.github/actions/just
        with:
          justfile_path: scripts/ci/justfile
          just_action: action-get-directories
